// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package client

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// Represents the state of an activity
type ActivityState string

const (
	// Activity is created
	ActivityStateCreated ActivityState = "CREATED"
	// Activity is active or in progress
	ActivityStateActive ActivityState = "ACTIVE"
	// Activity is done
	ActivityStateCompleted ActivityState = "COMPLETED"
	// Activity is ready to be started
	ActivityStateReady ActivityState = "READY"
	// Activity is invalid
	ActivityStateInvalid ActivityState = "INVALID"
	// Activity, like a set, has been called to start
	ActivityStateCalled ActivityState = "CALLED"
	// Activity is queued to run
	ActivityStateQueued ActivityState = "QUEUED"
)

var AllActivityState = []ActivityState{
	ActivityStateCreated,
	ActivityStateActive,
	ActivityStateCompleted,
	ActivityStateReady,
	ActivityStateInvalid,
	ActivityStateCalled,
	ActivityStateQueued,
}

// EventResultsEvent includes the requested fields of the GraphQL type Event.
// The GraphQL type's documentation follows.
//
// An event in a tournament
type EventResultsEvent struct {
	Id ID `json:"id"`
	// Title of event set by organizer
	Name string `json:"name"`
	// How much it costs to enter this event
	EntryFee float64 `json:"entryFee"`
	// Gets the number of entrants in this event
	NumEntrants int `json:"numEntrants"`
	// When does this event start?
	StartAt    int64                       `json:"startAt"`
	Tournament EventResultsEventTournament `json:"tournament"`
	// The state of the Event.
	State ActivityState `json:"state"`
	// Paginated sets for this Event
	Sets EventResultsEventSetsSetConnection `json:"sets"`
	// Paginated list of standings
	Standings EventResultsEventStandingsStandingConnection `json:"standings"`
}

// GetId returns EventResultsEvent.Id, and is useful for accessing the field via an interface.
func (v *EventResultsEvent) GetId() ID { return v.Id }

// GetName returns EventResultsEvent.Name, and is useful for accessing the field via an interface.
func (v *EventResultsEvent) GetName() string { return v.Name }

// GetEntryFee returns EventResultsEvent.EntryFee, and is useful for accessing the field via an interface.
func (v *EventResultsEvent) GetEntryFee() float64 { return v.EntryFee }

// GetNumEntrants returns EventResultsEvent.NumEntrants, and is useful for accessing the field via an interface.
func (v *EventResultsEvent) GetNumEntrants() int { return v.NumEntrants }

// GetStartAt returns EventResultsEvent.StartAt, and is useful for accessing the field via an interface.
func (v *EventResultsEvent) GetStartAt() int64 { return v.StartAt }

// GetTournament returns EventResultsEvent.Tournament, and is useful for accessing the field via an interface.
func (v *EventResultsEvent) GetTournament() EventResultsEventTournament { return v.Tournament }

// GetState returns EventResultsEvent.State, and is useful for accessing the field via an interface.
func (v *EventResultsEvent) GetState() ActivityState { return v.State }

// GetSets returns EventResultsEvent.Sets, and is useful for accessing the field via an interface.
func (v *EventResultsEvent) GetSets() EventResultsEventSetsSetConnection { return v.Sets }

// GetStandings returns EventResultsEvent.Standings, and is useful for accessing the field via an interface.
func (v *EventResultsEvent) GetStandings() EventResultsEventStandingsStandingConnection {
	return v.Standings
}

// EventResultsEventSetsSetConnection includes the requested fields of the GraphQL type SetConnection.
type EventResultsEventSetsSetConnection struct {
	Nodes []EventResultsEventSetsSetConnectionNodesSet `json:"nodes"`
}

// GetNodes returns EventResultsEventSetsSetConnection.Nodes, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnection) GetNodes() []EventResultsEventSetsSetConnectionNodesSet {
	return v.Nodes
}

// EventResultsEventSetsSetConnectionNodesSet includes the requested fields of the GraphQL type Set.
// The GraphQL type's documentation follows.
//
// A set
type EventResultsEventSetsSetConnectionNodesSet struct {
	Id ID `json:"id"`
	// Full round text of this set.
	FullRoundText string `json:"fullRoundText"`
	// The round number of the set. Negative numbers are losers bracket
	Round    int `json:"round"`
	State    int `json:"state"`
	WinnerId int `json:"winnerId"`
	// A possible spot in a set. Use this to get all entrants in a set. Use this for all bracket types (FFA, elimination, etc)
	Slots []EventResultsEventSetsSetConnectionNodesSetSlotsSetSlot `json:"slots"`
}

// GetId returns EventResultsEventSetsSetConnectionNodesSet.Id, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSet) GetId() ID { return v.Id }

// GetFullRoundText returns EventResultsEventSetsSetConnectionNodesSet.FullRoundText, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSet) GetFullRoundText() string {
	return v.FullRoundText
}

// GetRound returns EventResultsEventSetsSetConnectionNodesSet.Round, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSet) GetRound() int { return v.Round }

// GetState returns EventResultsEventSetsSetConnectionNodesSet.State, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSet) GetState() int { return v.State }

// GetWinnerId returns EventResultsEventSetsSetConnectionNodesSet.WinnerId, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSet) GetWinnerId() int { return v.WinnerId }

// GetSlots returns EventResultsEventSetsSetConnectionNodesSet.Slots, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSet) GetSlots() []EventResultsEventSetsSetConnectionNodesSetSlotsSetSlot {
	return v.Slots
}

// EventResultsEventSetsSetConnectionNodesSetSlotsSetSlot includes the requested fields of the GraphQL type SetSlot.
// The GraphQL type's documentation follows.
//
// A slot in a set where a seed currently or will eventually exist in order to participate in the set.
type EventResultsEventSetsSetConnectionNodesSetSlotsSetSlot struct {
	Entrant EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotEntrant `json:"entrant"`
	// The standing within this set for the seed currently assigned to this slot.
	Standing EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStanding `json:"standing"`
}

// GetEntrant returns EventResultsEventSetsSetConnectionNodesSetSlotsSetSlot.Entrant, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSetSlotsSetSlot) GetEntrant() EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotEntrant {
	return v.Entrant
}

// GetStanding returns EventResultsEventSetsSetConnectionNodesSetSlotsSetSlot.Standing, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSetSlotsSetSlot) GetStanding() EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStanding {
	return v.Standing
}

// EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotEntrant includes the requested fields of the GraphQL type Entrant.
// The GraphQL type's documentation follows.
//
// An entrant in an event
type EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotEntrant struct {
	Id ID `json:"id"`
	// The entrant name as it appears in bracket: gamerTag of the participant or team name
	Name string `json:"name"`
}

// GetId returns EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotEntrant.Id, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotEntrant) GetId() ID { return v.Id }

// GetName returns EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotEntrant.Name, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotEntrant) GetName() string {
	return v.Name
}

// EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStanding includes the requested fields of the GraphQL type Standing.
// The GraphQL type's documentation follows.
//
// A standing indicates the placement of something within a container.
type EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStanding struct {
	Stats EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStats `json:"stats"`
}

// GetStats returns EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStanding.Stats, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStanding) GetStats() EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStats {
	return v.Stats
}

// EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStats includes the requested fields of the GraphQL type StandingStats.
// The GraphQL type's documentation follows.
//
// Any stats related to this standing. This type is experimental and very likely to change in the future.
type EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStats struct {
	Score EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStatsScore `json:"score"`
}

// GetScore returns EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStats.Score, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStats) GetScore() EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStatsScore {
	return v.Score
}

// EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStatsScore includes the requested fields of the GraphQL type Score.
// The GraphQL type's documentation follows.
//
// The score that led to this standing being awarded. The meaning of this field can
// vary by standing type and is not used for some standing types.
type EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStatsScore struct {
	// The raw score value
	Value float64 `json:"value"`
}

// GetValue returns EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStatsScore.Value, and is useful for accessing the field via an interface.
func (v *EventResultsEventSetsSetConnectionNodesSetSlotsSetSlotStandingStatsScore) GetValue() float64 {
	return v.Value
}

// EventResultsEventStandingsStandingConnection includes the requested fields of the GraphQL type StandingConnection.
type EventResultsEventStandingsStandingConnection struct {
	Nodes []EventResultsEventStandingsStandingConnectionNodesStanding `json:"nodes"`
}

// GetNodes returns EventResultsEventStandingsStandingConnection.Nodes, and is useful for accessing the field via an interface.
func (v *EventResultsEventStandingsStandingConnection) GetNodes() []EventResultsEventStandingsStandingConnectionNodesStanding {
	return v.Nodes
}

// EventResultsEventStandingsStandingConnectionNodesStanding includes the requested fields of the GraphQL type Standing.
// The GraphQL type's documentation follows.
//
// A standing indicates the placement of something within a container.
type EventResultsEventStandingsStandingConnectionNodesStanding struct {
	Placement int `json:"placement"`
	// If the entity this standing is assigned to can be resolved into an entrant, this will provide the entrant.
	Entrant EventResultsEventStandingsStandingConnectionNodesStandingEntrant `json:"entrant"`
}

// GetPlacement returns EventResultsEventStandingsStandingConnectionNodesStanding.Placement, and is useful for accessing the field via an interface.
func (v *EventResultsEventStandingsStandingConnectionNodesStanding) GetPlacement() int {
	return v.Placement
}

// GetEntrant returns EventResultsEventStandingsStandingConnectionNodesStanding.Entrant, and is useful for accessing the field via an interface.
func (v *EventResultsEventStandingsStandingConnectionNodesStanding) GetEntrant() EventResultsEventStandingsStandingConnectionNodesStandingEntrant {
	return v.Entrant
}

// EventResultsEventStandingsStandingConnectionNodesStandingEntrant includes the requested fields of the GraphQL type Entrant.
// The GraphQL type's documentation follows.
//
// An entrant in an event
type EventResultsEventStandingsStandingConnectionNodesStandingEntrant struct {
	Participants []EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipant `json:"participants"`
}

// GetParticipants returns EventResultsEventStandingsStandingConnectionNodesStandingEntrant.Participants, and is useful for accessing the field via an interface.
func (v *EventResultsEventStandingsStandingConnectionNodesStandingEntrant) GetParticipants() []EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipant {
	return v.Participants
}

// EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipant includes the requested fields of the GraphQL type Participant.
// The GraphQL type's documentation follows.
//
// A participant of a tournament; either a spectator or competitor
type EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipant struct {
	// The tag that was used when the participant registered, e.g. Mang0
	GamerTag string                                                                                        `json:"gamerTag"`
	Player   EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipantPlayer `json:"player"`
}

// GetGamerTag returns EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipant.GamerTag, and is useful for accessing the field via an interface.
func (v *EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipant) GetGamerTag() string {
	return v.GamerTag
}

// GetPlayer returns EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipant.Player, and is useful for accessing the field via an interface.
func (v *EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipant) GetPlayer() EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipantPlayer {
	return v.Player
}

// EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipantPlayer includes the requested fields of the GraphQL type Player.
// The GraphQL type's documentation follows.
//
// A player
type EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipantPlayer struct {
	Id       ID     `json:"id"`
	GamerTag string `json:"gamerTag"`
}

// GetId returns EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipantPlayer.Id, and is useful for accessing the field via an interface.
func (v *EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipantPlayer) GetId() ID {
	return v.Id
}

// GetGamerTag returns EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipantPlayer.GamerTag, and is useful for accessing the field via an interface.
func (v *EventResultsEventStandingsStandingConnectionNodesStandingEntrantParticipantsParticipantPlayer) GetGamerTag() string {
	return v.GamerTag
}

// EventResultsEventTournament includes the requested fields of the GraphQL type Tournament.
// The GraphQL type's documentation follows.
//
// A tournament
type EventResultsEventTournament struct {
	VenueName    string `json:"venueName"`
	VenueAddress string `json:"venueAddress"`
}

// GetVenueName returns EventResultsEventTournament.VenueName, and is useful for accessing the field via an interface.
func (v *EventResultsEventTournament) GetVenueName() string { return v.VenueName }

// GetVenueAddress returns EventResultsEventTournament.VenueAddress, and is useful for accessing the field via an interface.
func (v *EventResultsEventTournament) GetVenueAddress() string { return v.VenueAddress }

// EventResultsResponse is returned by EventResults on success.
type EventResultsResponse struct {
	// Returns an event given its id or slug
	Event EventResultsEvent `json:"event"`
}

// GetEvent returns EventResultsResponse.Event, and is useful for accessing the field via an interface.
func (v *EventResultsResponse) GetEvent() EventResultsEvent { return v.Event }

// LeagueEventsLeague includes the requested fields of the GraphQL type League.
// The GraphQL type's documentation follows.
//
// A league
type LeagueEventsLeague struct {
	Id ID `json:"id"`
	// The tournament name
	Name string `json:"name"`
	// Paginated list of events in a league
	Events LeagueEventsLeagueEventsEventConnection `json:"events"`
}

// GetId returns LeagueEventsLeague.Id, and is useful for accessing the field via an interface.
func (v *LeagueEventsLeague) GetId() ID { return v.Id }

// GetName returns LeagueEventsLeague.Name, and is useful for accessing the field via an interface.
func (v *LeagueEventsLeague) GetName() string { return v.Name }

// GetEvents returns LeagueEventsLeague.Events, and is useful for accessing the field via an interface.
func (v *LeagueEventsLeague) GetEvents() LeagueEventsLeagueEventsEventConnection { return v.Events }

// LeagueEventsLeagueEventsEventConnection includes the requested fields of the GraphQL type EventConnection.
type LeagueEventsLeagueEventsEventConnection struct {
	Nodes []LeagueEventsLeagueEventsEventConnectionNodesEvent `json:"nodes"`
}

// GetNodes returns LeagueEventsLeagueEventsEventConnection.Nodes, and is useful for accessing the field via an interface.
func (v *LeagueEventsLeagueEventsEventConnection) GetNodes() []LeagueEventsLeagueEventsEventConnectionNodesEvent {
	return v.Nodes
}

// LeagueEventsLeagueEventsEventConnectionNodesEvent includes the requested fields of the GraphQL type Event.
// The GraphQL type's documentation follows.
//
// An event in a tournament
type LeagueEventsLeagueEventsEventConnectionNodesEvent struct {
	Id ID `json:"id"`
	// Title of event set by organizer
	Name       string                                                      `json:"name"`
	Tournament LeagueEventsLeagueEventsEventConnectionNodesEventTournament `json:"tournament"`
}

// GetId returns LeagueEventsLeagueEventsEventConnectionNodesEvent.Id, and is useful for accessing the field via an interface.
func (v *LeagueEventsLeagueEventsEventConnectionNodesEvent) GetId() ID { return v.Id }

// GetName returns LeagueEventsLeagueEventsEventConnectionNodesEvent.Name, and is useful for accessing the field via an interface.
func (v *LeagueEventsLeagueEventsEventConnectionNodesEvent) GetName() string { return v.Name }

// GetTournament returns LeagueEventsLeagueEventsEventConnectionNodesEvent.Tournament, and is useful for accessing the field via an interface.
func (v *LeagueEventsLeagueEventsEventConnectionNodesEvent) GetTournament() LeagueEventsLeagueEventsEventConnectionNodesEventTournament {
	return v.Tournament
}

// LeagueEventsLeagueEventsEventConnectionNodesEventTournament includes the requested fields of the GraphQL type Tournament.
// The GraphQL type's documentation follows.
//
// A tournament
type LeagueEventsLeagueEventsEventConnectionNodesEventTournament struct {
	Id ID `json:"id"`
	// The tournament name
	Name string `json:"name"`
}

// GetId returns LeagueEventsLeagueEventsEventConnectionNodesEventTournament.Id, and is useful for accessing the field via an interface.
func (v *LeagueEventsLeagueEventsEventConnectionNodesEventTournament) GetId() ID { return v.Id }

// GetName returns LeagueEventsLeagueEventsEventConnectionNodesEventTournament.Name, and is useful for accessing the field via an interface.
func (v *LeagueEventsLeagueEventsEventConnectionNodesEventTournament) GetName() string { return v.Name }

// LeagueEventsResponse is returned by LeagueEvents on success.
type LeagueEventsResponse struct {
	// Returns a league given its id or slug
	League LeagueEventsLeague `json:"league"`
}

// GetLeague returns LeagueEventsResponse.League, and is useful for accessing the field via an interface.
func (v *LeagueEventsResponse) GetLeague() LeagueEventsLeague { return v.League }

// TournamentEventsResponse is returned by TournamentEvents on success.
type TournamentEventsResponse struct {
	// Returns a tournament given its id or slug
	Tournament TournamentEventsTournament `json:"tournament"`
}

// GetTournament returns TournamentEventsResponse.Tournament, and is useful for accessing the field via an interface.
func (v *TournamentEventsResponse) GetTournament() TournamentEventsTournament { return v.Tournament }

// TournamentEventsTournament includes the requested fields of the GraphQL type Tournament.
// The GraphQL type's documentation follows.
//
// A tournament
type TournamentEventsTournament struct {
	Id ID `json:"id"`
	// The tournament name
	Name   string                                  `json:"name"`
	Events []TournamentEventsTournamentEventsEvent `json:"events"`
}

// GetId returns TournamentEventsTournament.Id, and is useful for accessing the field via an interface.
func (v *TournamentEventsTournament) GetId() ID { return v.Id }

// GetName returns TournamentEventsTournament.Name, and is useful for accessing the field via an interface.
func (v *TournamentEventsTournament) GetName() string { return v.Name }

// GetEvents returns TournamentEventsTournament.Events, and is useful for accessing the field via an interface.
func (v *TournamentEventsTournament) GetEvents() []TournamentEventsTournamentEventsEvent {
	return v.Events
}

// TournamentEventsTournamentEventsEvent includes the requested fields of the GraphQL type Event.
// The GraphQL type's documentation follows.
//
// An event in a tournament
type TournamentEventsTournamentEventsEvent struct {
	Id ID `json:"id"`
	// Title of event set by organizer
	Name string `json:"name"`
}

// GetId returns TournamentEventsTournamentEventsEvent.Id, and is useful for accessing the field via an interface.
func (v *TournamentEventsTournamentEventsEvent) GetId() ID { return v.Id }

// GetName returns TournamentEventsTournamentEventsEvent.Name, and is useful for accessing the field via an interface.
func (v *TournamentEventsTournamentEventsEvent) GetName() string { return v.Name }

// __EventResultsInput is used internally by genqlient
type __EventResultsInput struct {
	EventId ID  `json:"eventId"`
	Page    int `json:"page"`
}

// GetEventId returns __EventResultsInput.EventId, and is useful for accessing the field via an interface.
func (v *__EventResultsInput) GetEventId() ID { return v.EventId }

// GetPage returns __EventResultsInput.Page, and is useful for accessing the field via an interface.
func (v *__EventResultsInput) GetPage() int { return v.Page }

// __LeagueEventsInput is used internally by genqlient
type __LeagueEventsInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __LeagueEventsInput.Slug, and is useful for accessing the field via an interface.
func (v *__LeagueEventsInput) GetSlug() string { return v.Slug }

// __TournamentEventsInput is used internally by genqlient
type __TournamentEventsInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __TournamentEventsInput.Slug, and is useful for accessing the field via an interface.
func (v *__TournamentEventsInput) GetSlug() string { return v.Slug }

// The query executed by EventResults.
const EventResults_Operation = `
query EventResults ($eventId: ID!, $page: Int!) {
	event(id: $eventId) {
		id
		name
		entryFee
		numEntrants
		startAt
		tournament {
			venueName
			venueAddress
		}
		state
		sets(page: $page, perPage: 10) {
			nodes {
				id
				fullRoundText
				round
				state
				winnerId
				slots {
					entrant {
						id
						name
					}
					standing {
						stats {
							score {
								value
							}
						}
					}
				}
			}
		}
		standings(query: {page:$page,perPage:100}) {
			nodes {
				placement
				entrant {
					participants {
						gamerTag
						player {
							id
							gamerTag
						}
					}
				}
			}
		}
	}
}
`

func EventResults(
	ctx_ context.Context,
	client_ graphql.Client,
	eventId ID,
	page int,
) (data_ *EventResultsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "EventResults",
		Query:  EventResults_Operation,
		Variables: &__EventResultsInput{
			EventId: eventId,
			Page:    page,
		},
	}

	data_ = &EventResultsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by LeagueEvents.
const LeagueEvents_Operation = `
query LeagueEvents ($slug: String!) {
	league(slug: $slug) {
		id
		name
		events {
			nodes {
				id
				name
				tournament {
					id
					name
				}
			}
		}
	}
}
`

func LeagueEvents(
	ctx_ context.Context,
	client_ graphql.Client,
	slug string,
) (data_ *LeagueEventsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "LeagueEvents",
		Query:  LeagueEvents_Operation,
		Variables: &__LeagueEventsInput{
			Slug: slug,
		},
	}

	data_ = &LeagueEventsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by TournamentEvents.
const TournamentEvents_Operation = `
query TournamentEvents ($slug: String!) {
	tournament(slug: $slug) {
		id
		name
		events {
			id
			name
		}
	}
}
`

func TournamentEvents(
	ctx_ context.Context,
	client_ graphql.Client,
	slug string,
) (data_ *TournamentEventsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "TournamentEvents",
		Query:  TournamentEvents_Operation,
		Variables: &__TournamentEventsInput{
			Slug: slug,
		},
	}

	data_ = &TournamentEventsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
