query LeagueEvents($slug: String!) {
  league(slug: $slug) {
    id
    name
    events {
      nodes {
        id
        name
        tournament {
          id
          name
        }
      }
    }
  }
}

query TournamentEvents($slug: String!) {
  tournament(slug: $slug) {
    id
    name
    events {
      id
      name
    }
  }
}

query EventResults($eventId: ID!, $page: Int!) {
    event(id: $eventId) {
        id
        name
        entryFee
        numEntrants
        startAt
        tournament {
            venueName
            venueAddress
        }
        state
        sets(page: $page, perPage: 10) {
            nodes {
                id
                fullRoundText
                round
                state
                winnerId
                slots {
                    entrant {
                        id
                        name
                    }
                    standing {
                        stats {
                            score {
                                value
                            }
                        }
                    }
                }
            }
        }
        standings(query: {page: $page, perPage: 100}) {
            nodes {
                placement
                entrant {
                    participants {
                        gamerTag
                        player {
                            id
                            gamerTag
                        }
                    }
                }
            }
        }
    }
}